colors = ["red", "green", "blue", "yellow"] 
print(colors)
print(colors[3])
colors.append("purple")
print(colors)
colors.insert(1, "orange")
print(colors)
colors.remove("green")
print(colors)
index_of_blue = colors.index("blue")
print(index_of_blue)
colors.append("pink")
print(colors)
blue_count = colors.count("pink")
print(blue_count)
colors.sort()
print(colors)
colors.reverse()
print(colors)

